version: '3'

vars:
  COMPOSE_FILE: docker-compose.yml

tasks:
  default:
    desc: "Show available tasks"
    cmds:
      - task --list

  setup:
    desc: "Complete Ubuntu Redis Cluster setup (all steps)"
    cmds:
      - task: stop-cluster
      - task: start-cluster
      - task: wait-cluster
      - task: status

  start-cluster:
    desc: "Start Redis Cluster"
    silent: true
    cmds:
      - |
        echo "🚀 Step 4: Starting Redis Cluster..."
        docker compose -f {{.COMPOSE_FILE}} up -d
        echo "✅ Cluster started"
        echo ""

  stop-cluster:
    desc: "Stop existing cluster"
    silent: true
    cmds:
      - |
        echo "🛑 Step 3: Stopping existing cluster..."
        docker compose -f {{.COMPOSE_FILE}} down 2>/dev/null || true
        echo "✅ Cluster stopped"
        echo ""

  wait-cluster:
    desc: "Wait for cluster to be ready"
    silent: true
    cmds:
      - |
        echo "⏳ Step 5: Waiting for cluster to form (this takes ~15-20 seconds)..."
        sleep 5
        echo "   Checking cluster status..."
        
        # Wait up to 30 seconds for cluster to be ready
        for i in {1..30}; do
          if docker exec redis-7001 redis-cli -p 7001 cluster info 2>/dev/null | grep -q "cluster_state:ok"; then
            echo "✅ Cluster is ready!"
            break
          fi
          echo "   Waiting... ($i/30)"
          sleep 1
        done
        echo ""

  status:
    desc: "Show cluster status"
    silent: true
    cmds:
      - |
        echo "📊 Cluster Status:"
        echo "=================="
        docker exec redis-7001 redis-cli -p 7001 cluster info | grep -E "cluster_state|cluster_slots|cluster_known_nodes"
        echo ""
        echo "🎉 Setup Complete!"
        echo "=================="
        echo ""
        echo "Cluster Nodes:"
        docker exec redis-7001 redis-cli -p 7001 cluster nodes | grep -E "master|slave" | head -6
        echo ""
        echo "📝 Next Steps:"
        echo "   1. Info redis-cluster: docker exec redis-7001 redis-cli -p 7001 cluster info"
        echo "   2. Run Go example: cd app && go run example.go"
        echo "   3. View logs: docker logs redis-init-cluster"
        echo ""
        echo "✅ Your Redis Cluster is ready at localhost:7001-7006"

  restart:
    desc: "Restart the cluster"
    cmds:
      - task: stop-cluster
      - task: start-cluster
      - task: wait-cluster
      - task: status

  nodes:
    desc: "Show cluster nodes"
    cmds:
      - docker exec redis-7001 redis-cli -p 7001 cluster nodes

  info:
    desc: "Show cluster info"
    cmds:
      - docker exec redis-7001 redis-cli -p 7001 cluster info

  go-test:
    desc: "Run Go test connection"
    dir: app
    cmds:
      - go run test-connection.go

  go-example:
    desc: "Run Go example"
    dir: app
    cmds:
      - go run example.go